# --------------------
#       Vectors
# --------------------

dataStructures <- c("vector", "matrix", "array", "data frame", "list")
dataStructures

# Default type of data structure is a VECTOR
# Vectors can be thought of as contiguous cells containing data
# c() combines objects into a vector
age <- c(10, 20, 30, 40)
age

# Get single value
age[3]  # NOTE: Index is 1 based (not 0)

# Get slice of a vector
age[2:4]

# Get all excluding second element
age[-2]

# SCALARS are vectors of length 1
temperature <- 32
temperature

# Additional elements can be stored
temperature[2] <- 36.5
temperature  # NOTE: The mode of the vector changed from integer to double since 36.5 is a double
temperature[3] <- "37"
temperature  # NOTE: The mode of the vector changed from double to string since "37" is a string

# Logical vector
logical <- c(TRUE, FALSE, TRUE, FALSE)
logical

# The vector logical contains four logical constants
# A logical vector can be used as a row selector for another vector
age[logical]  # NOTE: Only elements with indexes corresponding to TRUE are selected
  
# COMBINE
# The function c combines its parameters to form a vector
# All parameters are coerced to a common type, which is the highest type of the parameters in the hierarchy:
# NULL < raw < logical < integer < double < complex < character< list < expression
combo <- c(1, "MALE", TRUE)
combo

# The function c can be used to select particular elements from a vector
# The following example creates a vector of six characters and selects the elements with indexes 1, 3, and 5
letters <- c("A","B","C","D","E","F")
letters
letters[c(1,3,5)]
# Exclude elements at indexes 1, 3, and 4
letters[-c(1,3,4)]
# Exclude a range
letters[-(3:4)]
# Include only range
letters[3:4]

# Vector Arithmetic
x <- c(2,3,4)
y <- c(1,2,3)
x+y
x+1
x*2
z <- c(2,1,2,1,2,1)
x+z

# Vector Arithmetic - Functions
# Max
max(x)
min(x)
sum(x)
prod(x)
sort(z)
length(z)


# Sequences
x <- 1:10
x
x <- 2*1:10-1 # The colon operator has higher precedence than arithmetic operators
x
11:3  # Backwards sequences
seq(1,10)  # 1:10 is equivalent to seq(1,10)
seq(-1,1,by=.2)
seq(length=10, from=-1, by=.5)
# Repeat
x <- c(1,2)
rep(x, times=3)  # Repeat the sequence 3 times
rep(x, each=3)  # Repeat each element 3 times, preserving the order or elements


# Logical Vectors
# Elements a logical vector can have the values TRUE, FALSE, and NA
log <- c(TRUE, TRUE, FALSE)
# TRUE and FALSE can be abbrevieated as T and F
log <- c(T,T,F)
# However, T and F are not reserved words and can be reassigned
T
T <- FALSE
T
# Logical vectors can be generated by logical conditions
x <- c(10,8,11)
log <- x>9
log
# In integer context, logical vectors are coerced to integers
FALSE+1
TRUE+1
FALSE:TRUE
# The logical operators are <, <=, >, >=, == for exact equality and != for inequality.
# Conjunction and Disjunction
log1 <- c(TRUE,FALSE,TRUE)
log2 <- c(FALSE,FALSE,TRUE)
log1 & log2
log1 | log2


# Special Values (NA, NaN, Inf)
# Infinity can be positive (Inf) or negative (-Inf)
1/0
-1/0
2^1024
-2^1024
# Nan stands for "Not a Number"
0/0
# NA represents "not available" or "missing value"
x <- c(NA,1,2)
2*x
# Check if value is NA
is.na(NA)
z <- c(1:3, NA)
is.na(z)


# Index Vectors
y <- z[!is.na(z)]
y
log <- c(TRUE,FALSE,TRUE)
x <- 1:9
x[log]

fruit <- c(5, 10, 1, 20)
names(fruit) <- c("orange", "banana", "apple", "peach")
lunch <- fruit[c("apple","orange")]
lunch



